name: Java CI with Maven and Docker  # Nome do workflow

on:
  push:
    branches: [main]  # Executa o workflow quando houver push na branch main
  pull_request:
    branches: [main]  # Executa o workflow para pull requests direcionados à branch main

jobs:
  build:
    runs-on: ubuntu-latest  # Define que o job vai rodar numa VM Ubuntu atualizada

    steps:
      - name: Checkout repository  # Passo para baixar o código do repositório
        uses: actions/checkout@v3

      - name: Set up JDK 17  # Passo para configurar o JDK 17 na VM
        uses: actions/setup-java@v3
        with:
          java-version: '17'  # Define a versão do Java que será usada
          distribution: 'temurin'  # Define a distribuição do Java (Temurin é uma distribuição OpenJDK)

      - name: Run Maven tests  # Roda os testes automatizados
        run: mvn test

      - name: Build Docker image  # Passo que constrói a imagem Docker da aplicação
        run: docker build -t employee-crud:latest .

      - name: Run Docker container with Secrets  # Passo que roda o container Docker com as variáveis secretas do GitHub
        run: |
          docker run -d -p 8080:8080 \
            -e SPRING_DATASOURCE_URL=${{ secrets.SPRING_DATASOURCE_URL }} \
            -e SPRING_DATASOURCE_USERNAME=${{ secrets.SPRING_DATASOURCE_USERNAME }} \
            -e SPRING_DATASOURCE_PASSWORD=${{ secrets.SPRING_DATASOURCE_PASSWORD }} \
            --name employee-app \
            employee-crud:latest

          echo "Esperando aplicação subir..."
          sleep 15  # Aguarda o app subir

          echo "Testando endpoint do Swagger..."
          curl -f http://localhost:8080/swagger-ui.html

          echo "Parando o container..."
          docker stop employee-app
          docker rm employee-app
